// File generated by FlutterFire CLI or custom setup for GeoHub.
// Replace with the values from your Firebase Project Console.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyMockKeyForWeb1234567890abcdef',
    appId: '1:123456789000:web:abcdef0123456789',
    messagingSenderId: '123456789000',
    projectId: 'geohub-app',
    authDomain: 'geohub-app.firebaseapp.com',
    storageBucket: 'geohub-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATuw8I_C-ET-sRCK96yUi0HZft-bimavQ',
    appId: '1:926673539070:android:9e29ea21f5a16b379fbaaf',
    messagingSenderId: '926673539070',
    projectId: 'geo-hub-ba554',
    storageBucket: 'geo-hub-ba554.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyMockKeyForIos1234567890abcdef',
    appId: '1:123456789000:ios:abcdef0123456789',
    messagingSenderId: '123456789000',
    projectId: 'geohub-app',
    storageBucket: 'geohub-app.appspot.com',
    iosBundleId: 'com.club.geohub',
  );
}
